"""
CLAUDE.md Generator

Generates global (~/.claude/CLAUDE.md) and project-level (./CLAUDE.md)
configuration files based on environment analysis.
Non-destructive: merges with existing content.
"""

import os
from datetime import date
from pathlib import Path
from typing import Any, Dict, Optional


class ClaudeMdGenerator:
    """Generates CLAUDE.md files from environment analysis data."""

    def __init__(self, project_dir: Optional[str] = None):
        self.project_dir = Path(project_dir or os.getcwd()).resolve()
        self.home_dir = Path.home()

    # ── Global CLAUDE.md ───────────────────────────────────────────────

    def generate_global(
        self,
        analysis: Dict[str, Any],
        developer_name: str = "",
        mcp_servers: Optional[list] = None,
    ) -> str:
        """Generate global ~/.claude/CLAUDE.md content."""
        hw = analysis.get("hardware", {})
        langs = [l["name"] for l in analysis.get("languages", []) if l.get("primary")]
        frameworks = [f["name"] for f in analysis.get("frameworks", [])]
        stack = ", ".join(langs + frameworks) if (langs or frameworks) else "multi-language"

        gpu_line = ""
        if hw.get("gpu"):
            vram = f" {hw['vram_mb']}MB VRAM" if hw.get("vram_mb") else ""
            gpu_line = f"- Hardware: {hw.get('cpu', 'Unknown CPU')}, {hw['gpu']}{vram}"
            if hw.get("ollama_available"):
                gpu_line += ", Ollama available"

        sections = []

        sections.append("# Global Claude Code Configuration\n")
        sections.append(f"Generated by superclaude bootstrap on {date.today().isoformat()}\n")

        # Identity
        sections.append("## Identity & Context\n")
        if developer_name:
            sections.append(f"- Developer: {developer_name}")
        sections.append(f"- Primary stack: {stack}")
        if gpu_line:
            sections.append(gpu_line)
        sections.append("")

        # MCP Tool Policy
        if mcp_servers:
            sections.append("## MCP Tool Policy — PROACTIVE USAGE REQUIRED\n")
            sections.append(
                "You have access to MCP tools. DO NOT wait for explicit instructions to use them.\n"
                "Use them as part of your standard workflow for every task.\n"
            )

            sections.append("### Pre-Work Phase (before writing any code):\n")
            mcp_set = set(s.lower() for s in mcp_servers)

            if "sequential-thinking" in mcp_set or "sequential" in mcp_set:
                sections.append(
                    "- **Sequential Thinking**: Use for ANY task with 2+ steps. Plan before executing."
                )
            if "atlassian" in mcp_set or "jira" in mcp_set:
                sections.append(
                    "- **Atlassian**: Search Jira for related tickets and Confluence for architecture docs."
                )
            if "grepai" in mcp_set:
                sections.append(
                    "- **GrepAI**: Search the codebase for existing patterns, similar implementations, "
                    "and potential conflicts before writing new code."
                )
            if "sentry" in mcp_set:
                sections.append(
                    "- **Sentry**: Check for production errors in any module you're about to modify."
                )
            sections.append("")

            sections.append("### During Work:\n")
            if "docker" in mcp_set:
                sections.append(
                    "- **Docker**: Manage containers, run isolated tests, check logs without manual docker commands."
                )
            if "sequential-thinking" in mcp_set or "sequential" in mcp_set:
                sections.append(
                    "- **Sequential Thinking**: When you encounter unexpected complexity, stop and re-plan."
                )
            sections.append("")

            sections.append("### Post-Work Phase (after writing code):\n")
            if "sonarqube" in mcp_set:
                sections.append(
                    "- **SonarQube**: Run analysis on all changed files. Fix issues before presenting results."
                )
            if "sentry" in mcp_set:
                sections.append(
                    "- **Sentry**: Verify changes don't conflict with known error patterns."
                )
            if "atlassian" in mcp_set or "jira" in mcp_set:
                sections.append(
                    "- **Atlassian**: Add comments to related Jira tickets summarizing what was done."
                )
            sections.append("")

        # Agent Teams
        sections.append("## Agent Teams\n")
        sections.append(
            "Agent teams are enabled. For tasks where parallel exploration adds value,\n"
            "create a team with specialized teammates. Key commands:\n"
        )
        sections.append("- `/team-review` — Parallel code review (security + quality + performance)")
        sections.append("- `/team-debug` — Competing hypothesis investigation")
        sections.append("- `/team-build` — Parallel feature implementation with file ownership")
        sections.append("- `/team-research` — Multi-angle research and decision-making")
        sections.append("- `/team-refactor` — Safe parallel refactoring")
        sections.append("")
        sections.append(
            "**File ownership rule**: Each teammate owns distinct files. "
            "No two teammates edit the same file."
        )
        sections.append("")

        # Response Standards
        sections.append("## Response Standards\n")
        sections.append(
            "- When completing a task, provide a brief summary: what changed, why, which files, "
            "and any related tickets."
        )
        sections.append("- Never say \"I could use [tool]\" — just use it.")
        sections.append(
            "- If quality tools find issues, fix them before presenting the result."
        )
        sections.append("")

        return "\n".join(sections)

    # ── Project-Level CLAUDE.md ────────────────────────────────────────

    def generate_project(self, analysis: Dict[str, Any]) -> str:
        """Generate project-level ./CLAUDE.md content."""
        sections = []
        project_name = self.project_dir.name

        # Header
        sections.append(f"# {project_name}\n")
        sections.append(f"Generated by superclaude bootstrap on {date.today().isoformat()}\n")

        # Project Overview
        sections.append("## Project Overview\n")
        langs = ", ".join(l["name"] for l in analysis.get("languages", []))
        frameworks = ", ".join(f["name"] for f in analysis.get("frameworks", []))
        pkg_mgrs = ", ".join(p["name"] for p in analysis.get("package_managers", []))

        sections.append(f"- **Languages**: {langs or 'N/A'}")
        sections.append(f"- **Frameworks**: {frameworks or 'N/A'}")
        sections.append(f"- **Package managers**: {pkg_mgrs or 'N/A'}")

        git = analysis.get("git", {})
        if git.get("remote"):
            sections.append(f"- **Repository**: {git['remote']}")
        sections.append("")

        # Directory Structure
        dirs = analysis.get("directory_structure", [])
        if dirs:
            sections.append("## Directory Structure\n")
            sections.append("```")
            for d in dirs[:40]:  # Cap at 40 entries
                sections.append(d)
            if len(dirs) > 40:
                sections.append(f"... and {len(dirs) - 40} more directories")
            sections.append("```\n")

        # Development Workflow
        sections.append("## Development Workflow\n")
        scripts = analysis.get("scripts", {})

        # Package manager commands
        for pm in analysis.get("package_managers", []):
            if pm["name"] == "uv":
                sections.append("### Python (UV)\n")
                sections.append("**CRITICAL**: This project uses UV. Never use `pip` or `python` directly.\n")
                sections.append("```bash")
                sections.append("uv run pytest              # Run tests")
                sections.append("uv pip install <pkg>       # Install packages")
                sections.append("uv run python <script>     # Run scripts")
                sections.append("```\n")
            elif pm["name"] == "npm":
                sections.append("### JavaScript (npm)\n")
                sections.append("```bash")
                sections.append("npm install                # Install dependencies")
                sections.append("npm run build              # Build")
                sections.append("npm test                   # Run tests")
                sections.append("```\n")
            elif pm["name"] == "pnpm":
                sections.append("### JavaScript (pnpm)\n")
                sections.append("```bash")
                sections.append("pnpm install               # Install dependencies")
                sections.append("pnpm run build             # Build")
                sections.append("pnpm test                  # Run tests")
                sections.append("```\n")

        # Makefile targets
        if scripts.get("makefile"):
            sections.append("### Makefile Targets\n")
            sections.append("```bash")
            for target in scripts["makefile"][:15]:
                sections.append(f"make {target}")
            sections.append("```\n")

        # package.json scripts
        if scripts.get("package_json"):
            sections.append("### Package Scripts\n")
            sections.append("```bash")
            for script in scripts["package_json"][:15]:
                sections.append(f"npm run {script}")
            sections.append("```\n")

        # Testing
        test_fws = analysis.get("test_frameworks", [])
        if test_fws:
            sections.append("## Testing\n")
            for tf in test_fws:
                sections.append(f"- **Framework**: {tf['name']}")
                if tf.get("test_dirs"):
                    sections.append(f"- **Test directory**: {', '.join(tf['test_dirs'])}")
                if tf.get("config"):
                    sections.append(f"- **Config**: {tf['config']}")
            sections.append("")

        # Linting
        linters = analysis.get("linters", [])
        if linters:
            sections.append("## Code Quality\n")
            for lint in linters:
                sections.append(f"- **{lint['name']}**")
            sections.append("")

        # Docker
        docker = analysis.get("docker", {})
        if docker.get("compose_file") or docker.get("dockerfile"):
            sections.append("## Docker\n")
            if docker.get("compose_file"):
                sections.append(f"- **Compose file**: {docker['compose_file']}")
                if docker.get("services"):
                    sections.append(f"- **Services**: {', '.join(docker['services'])}")
            if docker.get("dockerfile"):
                sections.append(f"- **Dockerfile**: {docker['dockerfile']}")
            sections.append("")

        return "\n".join(sections)

    # ── File Operations ────────────────────────────────────────────────

    def write_global(
        self,
        content: str,
        merge: bool = True,
        dry_run: bool = False,
    ) -> str:
        """Write or merge global CLAUDE.md."""
        path = self.home_dir / ".claude" / "CLAUDE.md"
        return self._write_md(path, content, merge, dry_run)

    def write_project(
        self,
        content: str,
        merge: bool = True,
        dry_run: bool = False,
    ) -> str:
        """Write or merge project CLAUDE.md."""
        path = self.project_dir / "CLAUDE.md"
        return self._write_md(path, content, merge, dry_run)

    def _write_md(
        self,
        path: Path,
        new_content: str,
        merge: bool,
        dry_run: bool,
    ) -> str:
        """Write markdown file, optionally merging with existing content."""
        if dry_run:
            if path.exists() and merge:
                return f"[DRY RUN] Would merge new content into {path}"
            return f"[DRY RUN] Would create {path}"

        path.parent.mkdir(parents=True, exist_ok=True)

        BEGIN_MARKER = "<!-- BEGIN: superclaude bootstrap additions -->"
        END_MARKER = "<!-- END: superclaude bootstrap additions -->"

        if path.exists() and merge:
            existing = path.read_text()

            new_block = (
                BEGIN_MARKER + "\n\n"
                + new_content
                + "\n\n" + END_MARKER + "\n"
            )

            # Check if sentinel block already exists — replace it
            if BEGIN_MARKER in existing and END_MARKER in existing:
                begin_idx = existing.index(BEGIN_MARKER)
                end_idx = existing.index(END_MARKER) + len(END_MARKER)
                prefix = existing[:begin_idx].rstrip()
                suffix = existing[end_idx:].lstrip('\n')
                merged = prefix + "\n\n---\n\n" + new_block
                if suffix:
                    merged += "\n" + suffix
            else:
                # First time — append with separator
                merged = (
                    existing.rstrip()
                    + "\n\n---\n\n"
                    + new_block
                )

            path.write_text(merged)
            return f"Merged new content into {path}"
        else:
            path.write_text(new_content)
            return f"Created {path}"
