"""
Local LLM Integration

Hardware-adaptive local LLM offloading via Ollama.
Detects GPU/VRAM and recommends appropriate models.
"""

import json
import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ── Model Recommendations by VRAM ──────────────────────────────────────
# Organized by minimum VRAM required (in MB).

MODEL_TIERS = [
    {
        "min_vram_mb": 0,
        "max_vram_mb": 4096,
        "label": "Low VRAM (< 4GB)",
        "models": [
            {
                "name": "qwen2.5-coder:3b",
                "purpose": "Code generation and completion",
                "size": "~2GB",
            },
            {
                "name": "nomic-embed-text",
                "purpose": "Codebase embeddings for semantic search (GrepAI)",
                "size": "~300MB",
            },
        ],
    },
    {
        "min_vram_mb": 4096,
        "max_vram_mb": 8192,
        "label": "Medium VRAM (4-8GB)",
        "models": [
            {
                "name": "qwen2.5-coder:7b",
                "purpose": "Best balance of code generation quality and speed",
                "size": "~4.5GB",
            },
            {
                "name": "nomic-embed-text",
                "purpose": "Codebase embeddings for semantic search (GrepAI)",
                "size": "~300MB",
            },
        ],
    },
    {
        "min_vram_mb": 8192,
        "max_vram_mb": 12288,
        "label": "Good VRAM (8-12GB)",
        "models": [
            {
                "name": "qwen2.5-coder:7b",
                "purpose": "Code generation and completion (primary)",
                "size": "~4.5GB",
            },
            {
                "name": "deepseek-coder-v2:16b-lite-instruct-q4_K_M",
                "purpose": "Code understanding and analysis",
                "size": "~9GB",
            },
            {
                "name": "nomic-embed-text",
                "purpose": "Codebase embeddings for semantic search (GrepAI)",
                "size": "~300MB",
            },
        ],
    },
    {
        "min_vram_mb": 12288,
        "max_vram_mb": 999999,
        "label": "High VRAM (12GB+)",
        "models": [
            {
                "name": "qwen2.5-coder:14b",
                "purpose": "High-quality code generation",
                "size": "~9GB",
            },
            {
                "name": "deepseek-coder-v2:16b-lite-instruct-q4_K_M",
                "purpose": "Code understanding and analysis",
                "size": "~9GB",
            },
            {
                "name": "nomic-embed-text",
                "purpose": "Codebase embeddings for semantic search (GrepAI)",
                "size": "~300MB",
            },
        ],
    },
]

# ── Ollama Script Template ─────────────────────────────────────────────

OLLAMA_SCRIPT = """\
#!/bin/bash
# Local LLM Helper — Ollama integration for development tasks
# Generated by superclaude bootstrap
#
# Usage:
#   .claude/scripts/local-llm.sh status          # Check Ollama status
#   .claude/scripts/local-llm.sh setup            # Pull recommended models
#   .claude/scripts/local-llm.sh docs <file>      # Generate documentation
#   .claude/scripts/local-llm.sh stubs <file>     # Generate test stubs
#   .claude/scripts/local-llm.sh summarize <file> # Summarize a file
#   .claude/scripts/local-llm.sh query "<prompt>" # Free-form query

set -euo pipefail

OLLAMA_HOST="${{OLLAMA_HOST:-http://localhost:11434}}"
CODE_MODEL="${{OLLAMA_CODE_MODEL:-{code_model}}}"
EMBED_MODEL="${{OLLAMA_EMBED_MODEL:-nomic-embed-text}}"

# ── Helpers ────────────────────────────────────────────────────────────

check_ollama() {{
  if ! command -v ollama &>/dev/null; then
    echo "ERROR: Ollama is not installed."
    echo "Install: curl -fsSL https://ollama.com/install.sh | sh"
    exit 1
  fi

  if ! ollama list &>/dev/null 2>&1; then
    echo "ERROR: Ollama is not running."
    echo "Start: ollama serve"
    exit 1
  fi
}}

call_ollama() {{
  local model="$1"
  local prompt="$2"
  curl -s "$OLLAMA_HOST/api/generate" \\
    -d "$(jq -n --arg model "$model" --arg prompt "$prompt" \\
      '{{model: $model, prompt: $prompt, stream: false}}')" \\
    | jq -r '.response // .error // "No response"'
}}

# ── Commands ───────────────────────────────────────────────────────────

cmd_status() {{
  check_ollama
  echo "Ollama Status:"
  echo "  Host: $OLLAMA_HOST"
  echo "  Code model: $CODE_MODEL"
  echo "  Embed model: $EMBED_MODEL"
  echo ""
  echo "Installed models:"
  ollama list
}}

cmd_setup() {{
  check_ollama
  echo "Pulling recommended models..."
  echo "  Pulling $CODE_MODEL (this may take a while)..."
  ollama pull "$CODE_MODEL"
  echo "  Pulling $EMBED_MODEL..."
  ollama pull "$EMBED_MODEL"
  echo "Done! Models ready."
}}

cmd_docs() {{
  check_ollama
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found: $file"
    exit 1
  fi
  local content
  content=$(cat "$file")
  local prompt="Generate concise documentation for this code file. Include: purpose, key functions/classes, parameters, return values, and usage examples. Output as markdown.\\n\\nFile: $file\\n\\n$content"
  call_ollama "$CODE_MODEL" "$prompt"
}}

cmd_stubs() {{
  check_ollama
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found: $file"
    exit 1
  fi
  local content
  content=$(cat "$file")
  local prompt="Generate test stubs for every public function/method in this file. Use the project's test framework conventions. Include descriptive test names and basic assertions.\\n\\nFile: $file\\n\\n$content"
  call_ollama "$CODE_MODEL" "$prompt"
}}

cmd_summarize() {{
  check_ollama
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found: $file"
    exit 1
  fi
  local content
  content=$(cat "$file")
  local prompt="Summarize this code file in 2-3 sentences. State its purpose, key responsibilities, and how it fits into the larger system.\\n\\nFile: $file\\n\\n$content"
  call_ollama "$CODE_MODEL" "$prompt"
}}

cmd_query() {{
  check_ollama
  local prompt="$1"
  call_ollama "$CODE_MODEL" "$prompt"
}}

# ── Main ───────────────────────────────────────────────────────────────

case "${{1:-status}}" in
  status)    cmd_status ;;
  setup)     cmd_setup ;;
  docs)      cmd_docs "${{2:?Usage: local-llm.sh docs <file>}}" ;;
  stubs)     cmd_stubs "${{2:?Usage: local-llm.sh stubs <file>}}" ;;
  summarize) cmd_summarize "${{2:?Usage: local-llm.sh summarize <file>}}" ;;
  query)     cmd_query "${{2:?Usage: local-llm.sh query \\"<prompt>\\"}}" ;;
  *)
    echo "Usage: local-llm.sh {{status|setup|docs|stubs|summarize|query}} [args]"
    exit 1
    ;;
esac
"""


class LocalLlmManager:
    """Manages local LLM integration via Ollama."""

    def __init__(self, project_dir: Optional[str] = None):
        self.project_dir = Path(project_dir or os.getcwd()).resolve()
        self.scripts_dir = self.project_dir / ".claude" / "scripts"

    def detect_hardware(self) -> Dict[str, Any]:
        """Detect available GPU hardware and VRAM."""
        result = {"gpu": None, "vram_mb": None, "cuda_available": False}

        try:
            proc = subprocess.run(
                ["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader,nounits"],
                capture_output=True, text=True, timeout=5,
            )
            if proc.returncode == 0 and proc.stdout.strip():
                parts = proc.stdout.strip().split(",")
                result["gpu"] = parts[0].strip()
                result["cuda_available"] = True
                if len(parts) > 1:
                    try:
                        result["vram_mb"] = int(parts[1].strip())
                    except ValueError:
                        pass
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

        return result

    def recommend_models(self, vram_mb: Optional[int] = None) -> Dict[str, Any]:
        """Recommend models based on available VRAM."""
        if vram_mb is None:
            hw = self.detect_hardware()
            vram_mb = hw.get("vram_mb", 0) or 0

        for tier in MODEL_TIERS:
            if tier["min_vram_mb"] <= vram_mb < tier["max_vram_mb"]:
                return {
                    "tier": tier["label"],
                    "vram_mb": vram_mb,
                    "models": tier["models"],
                    "primary_code_model": tier["models"][0]["name"],
                }

        # Fallback: smallest tier
        return {
            "tier": MODEL_TIERS[0]["label"],
            "vram_mb": vram_mb,
            "models": MODEL_TIERS[0]["models"],
            "primary_code_model": MODEL_TIERS[0]["models"][0]["name"],
        }

    def check_ollama(self) -> Dict[str, Any]:
        """Check Ollama installation and status."""
        result = {"installed": False, "running": False, "models": []}

        try:
            proc = subprocess.run(
                ["ollama", "--version"],
                capture_output=True, text=True, timeout=5,
            )
            result["installed"] = proc.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return result

        try:
            proc = subprocess.run(
                ["ollama", "list"],
                capture_output=True, text=True, timeout=10,
            )
            if proc.returncode == 0:
                result["running"] = True
                lines = proc.stdout.strip().split("\n")
                if len(lines) > 1:
                    result["models"] = [
                        line.split()[0] for line in lines[1:] if line.strip()
                    ]
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

        return result

    def generate_script(self, vram_mb: Optional[int] = None) -> str:
        """Generate the local-llm.sh script with hardware-appropriate models."""
        rec = self.recommend_models(vram_mb)
        code_model = rec["primary_code_model"]
        return OLLAMA_SCRIPT.format(code_model=code_model)

    def install(
        self, vram_mb: Optional[int] = None, dry_run: bool = False
    ) -> Tuple[bool, str]:
        """Install the local LLM helper script."""
        script_content = self.generate_script(vram_mb)
        script_path = self.scripts_dir / "local-llm.sh"

        if dry_run:
            rec = self.recommend_models(vram_mb)
            lines = [
                f"Would create {script_path}",
                f"VRAM: {rec['vram_mb']}MB ({rec['tier']})",
                f"Primary model: {rec['primary_code_model']}",
                "Recommended models:",
            ]
            for m in rec["models"]:
                lines.append(f"  {m['name']:45} {m['purpose']} ({m['size']})")
            return True, "\n".join(lines)

        self.scripts_dir.mkdir(parents=True, exist_ok=True)

        script_path.write_text(script_content)
        # Make executable
        script_path.chmod(script_path.stat().st_mode | 0o755)

        rec = self.recommend_models(vram_mb)
        lines = [
            f"Created {script_path}",
            f"Configured for: {rec['tier']} ({rec['vram_mb']}MB VRAM)",
            f"Primary code model: {rec['primary_code_model']}",
            "",
            "Next steps:",
            "  1. Install Ollama: curl -fsSL https://ollama.com/install.sh | sh",
            "  2. Pull models: .claude/scripts/local-llm.sh setup",
            "  3. Use: .claude/scripts/local-llm.sh docs <file>",
        ]

        return True, "\n".join(lines)
