#!/bin/bash
# Local LLM Helper — Ollama integration for development tasks
# Generated by superclaude bootstrap
#
# Usage:
#   .claude/scripts/local-llm.sh status          # Check Ollama status
#   .claude/scripts/local-llm.sh setup            # Pull recommended models
#   .claude/scripts/local-llm.sh docs <file>      # Generate documentation
#   .claude/scripts/local-llm.sh stubs <file>     # Generate test stubs
#   .claude/scripts/local-llm.sh summarize <file> # Summarize a file
#   .claude/scripts/local-llm.sh query "<prompt>" # Free-form query

set -euo pipefail

OLLAMA_HOST="${OLLAMA_HOST:-http://localhost:11434}"
CODE_MODEL="${OLLAMA_CODE_MODEL:-qwen2.5-coder:7b}"
EMBED_MODEL="${OLLAMA_EMBED_MODEL:-nomic-embed-text}"

# ── Helpers ────────────────────────────────────────────────────────────

check_ollama() {
  if ! command -v ollama &>/dev/null; then
    echo "ERROR: Ollama is not installed."
    echo "Install: curl -fsSL https://ollama.com/install.sh | sh"
    exit 1
  fi

  if ! ollama list &>/dev/null 2>&1; then
    echo "ERROR: Ollama is not running."
    echo "Start: ollama serve"
    exit 1
  fi
}

call_ollama() {
  local model="$1"
  local prompt="$2"
  curl -s "$OLLAMA_HOST/api/generate" \
    -d "$(jq -n --arg model "$model" --arg prompt "$prompt" \
      '{model: $model, prompt: $prompt, stream: false}')" \
    | jq -r '.response // .error // "No response"'
}

# ── Commands ───────────────────────────────────────────────────────────

cmd_status() {
  check_ollama
  echo "Ollama Status:"
  echo "  Host: $OLLAMA_HOST"
  echo "  Code model: $CODE_MODEL"
  echo "  Embed model: $EMBED_MODEL"
  echo ""
  echo "Installed models:"
  ollama list
}

cmd_setup() {
  check_ollama
  echo "Pulling recommended models..."
  echo "  Pulling $CODE_MODEL (this may take a while)..."
  ollama pull "$CODE_MODEL"
  echo "  Pulling $EMBED_MODEL..."
  ollama pull "$EMBED_MODEL"
  echo "Done! Models ready."
}

cmd_docs() {
  check_ollama
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found: $file"
    exit 1
  fi
  local content
  content=$(cat "$file")
  local prompt="Generate concise documentation for this code file. Include: purpose, key functions/classes, parameters, return values, and usage examples. Output as markdown.\n\nFile: $file\n\n$content"
  call_ollama "$CODE_MODEL" "$prompt"
}

cmd_stubs() {
  check_ollama
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found: $file"
    exit 1
  fi
  local content
  content=$(cat "$file")
  local prompt="Generate test stubs for every public function/method in this file. Use the project's test framework conventions. Include descriptive test names and basic assertions.\n\nFile: $file\n\n$content"
  call_ollama "$CODE_MODEL" "$prompt"
}

cmd_summarize() {
  check_ollama
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found: $file"
    exit 1
  fi
  local content
  content=$(cat "$file")
  local prompt="Summarize this code file in 2-3 sentences. State its purpose, key responsibilities, and how it fits into the larger system.\n\nFile: $file\n\n$content"
  call_ollama "$CODE_MODEL" "$prompt"
}

cmd_query() {
  check_ollama
  local prompt="$1"
  call_ollama "$CODE_MODEL" "$prompt"
}

# ── Main ───────────────────────────────────────────────────────────────

case "${1:-status}" in
  status)    cmd_status ;;
  setup)     cmd_setup ;;
  docs)      cmd_docs "${2:?Usage: local-llm.sh docs <file>}" ;;
  stubs)     cmd_stubs "${2:?Usage: local-llm.sh stubs <file>}" ;;
  summarize) cmd_summarize "${2:?Usage: local-llm.sh summarize <file>}" ;;
  query)     cmd_query "${2:?Usage: local-llm.sh query \"<prompt>\"}" ;;
  *)
    echo "Usage: local-llm.sh {status|setup|docs|stubs|summarize|query} [args]"
    exit 1
    ;;
esac
